apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstackpvc
  namespace: bookstack-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage